### ISSUE TITLE
Local admin

### ISSUE THREAD

**Issue by damienlagae** [Enabel/Password#47]
Add a segmentation, allowing the local administrator to do "admin" actions for their staffs

## Actions:
- Check info
- Reset password
- Unlock account ?

## How to do ?
- 1 admin = 1 country ?
- 2 roles: Admin (ALL) & admin_local (Only field) ? 
- How to store the country of management ? Update from GO4HR? Manually? with expiration date ? ...

**Comment by thijsbraem** [comment]
Do we need a list of who those local administrators would be? "Official" HR focal points + IT colleagues?
